-- Expand muscle groups from 6 to 10 specific groups
-- Generated: 2026-05-16T01:42:52.252Z
--
-- Old groups: chest | back | legs | shoulders | arms | abs
-- New groups: chest | back | legs | shoulders | biceps | triceps | forearms | abs | glutes | calves
--
-- Steps:
--   1. Drop old check constraint
--   2. Update all exercises to specific muscle groups (using free-exercise-db data)
--   3. Set unmapped exercises default (abs)
--   4. Add new check constraint

-- Step 1: Drop old constraint
alter table exercises
  drop constraint if exists exercises_muscle_group_check;

-- Step 2: Update exercises by name using free-exercise-db muscle data
update exercises set muscle_group = 'abs'
where lower(name) in (
    '3/4 sit-up',
    'ab crunch machine',
    'ab roller',
    'advanced kettlebell windmill',
    'air bike',
    'alternate heel touchers',
    'barbell ab rollout',
    'barbell ab rollout - on knees',
    'barbell rollout from bench',
    'barbell side bend',
    'bent-knee hip raise',
    'bent press',
    'bosu ball cable crunch with side bends',
    'bottoms up',
    'butt-ups',
    'cable crunch',
    'cable judo flip',
    'cable reverse crunch',
    'cable russian twists',
    'cable seated crunch',
    'cocoons',
    'cross-body crunch',
    'crunch - hands overhead',
    'crunch - legs on exercise ball',
    'crunches',
    'dead bug',
    'decline crunch',
    'decline oblique crunch',
    'decline reverse crunch',
    'double kettlebell windmill',
    'dumbbell side bend',
    'elbow to knee',
    'exercise ball crunch',
    'exercise ball pull-in',
    'flat bench leg pull-in',
    'flat bench lying leg raise',
    'frog sit-ups',
    'gorilla chin/crunch',
    'hanging leg raise',
    'hanging pike',
    'jackknife sit-up',
    'janda sit-up',
    'kettlebell figure 8',
    'kettlebell pass between the legs',
    'kettlebell windmill',
    'knee/hip raise on parallel bars',
    'kneeling cable crunch with alternating oblique twists',
    'landmine 180''s',
    'leg pull-in',
    'lower back curl',
    'medicine ball full twist',
    'oblique crunches',
    'oblique crunches - on the floor',
    'one-arm high-pulley cable side bends',
    'one-arm medicine ball slam',
    'otis-up',
    'overhead stretch',
    'pallof press',
    'pallof press with rotation',
    'plank',
    'plate twist',
    'press sit-up',
    'reverse crunch',
    'rope crunch',
    'russian twist',
    'scissor kick',
    'seated barbell twist',
    'seated flat bench leg pull-in',
    'seated leg tucks',
    'seated overhead stretch',
    'side bridge',
    'side jackknife',
    'sit-up',
    'sledgehammer swings',
    'smith machine hip raise',
    'spell caster',
    'spider crawl',
    'standing cable lift',
    'standing cable wood chop',
    'standing lateral stretch',
    'standing rope crunch',
    'stomach vacuum',
    'supine one-arm overhead throw',
    'supine two-arm overhead throw',
    'suspended fallout',
    'suspended reverse crunch',
    'toe touchers',
    'torso rotation',
    'tuck crunch',
    'weighted ball side bend',
    'weighted crunches',
    'weighted sit-ups - with bands',
    'wind sprints'
);

update exercises set muscle_group = 'legs'
where lower(name) in (
    '90/90 hamstring',
    'adductor',
    'adductor/groin',
    'all fours quad stretch',
    'alternate leg diagonal bound',
    'alternating hang clean',
    'backward drag',
    'ball leg curl',
    'band good morning',
    'band good morning (pull through)',
    'band hip adductions',
    'barbell full squat',
    'barbell hack squat',
    'barbell lunge',
    'barbell side split squat',
    'barbell squat',
    'barbell squat to a bench',
    'barbell step ups',
    'barbell walking lunge',
    'bear crawl sled drags',
    'bench jump',
    'bench sprint',
    'bicycling',
    'bicycling, stationary',
    'bodyweight squat',
    'bodyweight walking lunge',
    'box jump (multiple response)',
    'box skip',
    'box squat',
    'box squat with bands',
    'box squat with chains',
    'cable deadlifts',
    'cable hip adduction',
    'car deadlift',
    'carioca quick step',
    'chair leg extended stretch',
    'chair squat',
    'clean',
    'clean deadlift',
    'clean pull',
    'clean from blocks',
    'conan''s wheel',
    'depth jump leap',
    'double kettlebell alternating hang clean',
    'double leg butt kick',
    'dumbbell clean',
    'dumbbell lunges',
    'dumbbell rear lunge',
    'dumbbell seated box jump',
    'dumbbell squat',
    'dumbbell squat to a bench',
    'dumbbell step ups',
    'elevated back lunge',
    'elliptical trainer',
    'fast skipping',
    'floor glute-ham raise',
    'frankenstein squat',
    'freehand jump squat',
    'frog hops',
    'front barbell squat',
    'front barbell squat to a bench',
    'front box jump',
    'front cone hops (or hurdle hops)',
    'front leg raises',
    'front squat (clean grip)',
    'front squats with two kettlebells',
    'glute ham raise',
    'goblet squat',
    'good morning',
    'good morning off pins',
    'groin and back stretch',
    'groiners',
    'hack squat',
    'hamstring-smr',
    'hamstring stretch',
    'hang clean',
    'hang clean - below the knees',
    'hang snatch',
    'hang snatch - below knees',
    'hanging bar good morning',
    'heaving snatch balance',
    'hip circles (prone)',
    'hip flexion with band',
    'hurdle hops',
    'it band and glute stretch',
    'iliotibial tract-smr',
    'inchworm',
    'intermediate groin stretch',
    'intermediate hip flexor and quad stretch',
    'iron crosses (stretch)',
    'jefferson squats',
    'jerk dip squat',
    'jogging, treadmill',
    'kettlebell dead clean',
    'kettlebell hang clean',
    'kettlebell one-legged deadlift',
    'kettlebell pistol squat',
    'knee tuck jump',
    'kneeling hip flexor',
    'lateral bound',
    'lateral box jump',
    'lateral cone hops',
    'leg-up hamstring stretch',
    'leg extensions',
    'leg press',
    'leverage deadlift',
    'linear 3-part start technique',
    'linear acceleration wall drill',
    'linear depth jump',
    'looking at ceiling',
    'lunge pass through',
    'lunge sprint',
    'lying bent leg groin',
    'lying crossover',
    'lying hamstring',
    'lying leg curls',
    'lying machine squat',
    'lying prone quadriceps',
    'monster walk',
    'mountain climbers',
    'moving claw series',
    'muscle snatch',
    'narrow stance hack squats',
    'narrow stance leg press',
    'narrow stance squats',
    'natural glute ham raise',
    'olympic squat',
    'on-your-back quad stretch',
    'on your side quad stretch',
    'one-arm kettlebell clean',
    'one-arm kettlebell swings',
    'one-arm open palm kettlebell clean',
    'one-arm overhead kettlebell squats',
    'one-arm side deadlift',
    'one half locust',
    'one leg barbell squat',
    'open palm kettlebell clean',
    'overhead squat',
    'platform hamstring slides',
    'plie dumbbell squat',
    'power clean',
    'power clean from blocks',
    'power jerk',
    'power snatch',
    'power snatch from blocks',
    'power stairs',
    'prone manual hamstring',
    'prowler sprint',
    'quad stretch',
    'quadriceps-smr',
    'quick leap',
    'rear leg raises',
    'recumbent bike',
    'reverse band box squat',
    'reverse band power squat',
    'reverse band sumo deadlift',
    'reverse hyperextension',
    'rickshaw deadlift',
    'rocket jump',
    'romanian deadlift',
    'romanian deadlift from deficit',
    'rope jumping',
    'rowing, stationary',
    'runner''s stretch',
    'running, treadmill',
    'sandbag load',
    'scissors jump',
    'seated band hamstring curl',
    'seated floor hamstring stretch',
    'seated hamstring',
    'seated hamstring and calf stretch',
    'seated leg curl',
    'side hop-sprint',
    'side leg raises',
    'side lying groin stretch',
    'side standing long jump',
    'side to side box shuffle',
    'single-cone sprint drill',
    'single-leg high box squat',
    'single-leg hop progression',
    'single-leg lateral hop',
    'single-leg leg extension',
    'single-leg stride jump',
    'single leg butt kick',
    'single leg push-off',
    'sit squats',
    'skating',
    'sled drag - harness',
    'sled push',
    'smith machine hang power clean',
    'smith machine leg press',
    'smith machine pistol squat',
    'smith machine squat',
    'smith machine stiff-legged deadlift',
    'smith single-leg split squat',
    'snatch',
    'snatch balance',
    'snatch deadlift',
    'snatch pull',
    'snatch from blocks',
    'speed box squat',
    'speed squats',
    'split clean',
    'split jerk',
    'split jump',
    'split snatch',
    'split squat with dumbbells',
    'split squats',
    'squat jerk',
    'squat with bands',
    'squat with chains',
    'squat with plate movers',
    'squats - with bands',
    'stairmaster',
    'standing elevated quad stretch',
    'standing hamstring and calf stretch',
    'standing hip circles',
    'standing hip flexors',
    'standing leg curl',
    'standing long jump',
    'standing toe touches',
    'star jump',
    'step mill',
    'stiff-legged barbell deadlift',
    'stiff-legged dumbbell deadlift',
    'stride jump crossover',
    'sumo deadlift',
    'sumo deadlift with bands',
    'sumo deadlift with chains',
    'suspended split squat',
    'the straddle',
    'thigh abductor',
    'thigh adductor',
    'tire flip',
    'trail running/walking',
    'trap bar deadlift',
    'upper back-leg grab',
    'vertical swing',
    'walking, treadmill',
    'weighted jump squat',
    'weighted sissy squat',
    'weighted squat',
    'wide stance barbell squat',
    'wide stance stiff legs',
    'windmills',
    'world''s greatest stretch',
    'yoke walk',
    'zercher squats'
);

update exercises set muscle_group = 'biceps'
where lower(name) in (
    'alternate hammer curl',
    'alternate incline dumbbell curl',
    'barbell curl',
    'barbell curls lying against an incline',
    'brachialis-smr',
    'cable hammer curls - rope attachment',
    'cable preacher curl',
    'close-grip ez-bar curl with band',
    'close-grip ez bar curl',
    'close-grip standing barbell curl',
    'concentration curls',
    'cross body hammer curl',
    'drag curl',
    'dumbbell alternate bicep curl',
    'dumbbell bicep curl',
    'dumbbell prone incline curl',
    'ez-bar curl',
    'flexor incline dumbbell curls',
    'hammer curls',
    'high cable curls',
    'incline dumbbell curl',
    'incline hammer curls',
    'incline inner biceps curl',
    'lying cable curl',
    'lying close-grip bar curl on high pulley',
    'lying high bench barbell curl',
    'lying supine dumbbell curl',
    'machine bicep curl',
    'machine preacher curls',
    'one arm dumbbell preacher curl',
    'overhead cable curl',
    'preacher curl',
    'preacher hammer dumbbell curl',
    'reverse barbell curl',
    'reverse barbell preacher curls',
    'reverse cable curl',
    'reverse plate curls',
    'seated biceps',
    'seated close-grip concentration barbell curl',
    'seated dumbbell curl',
    'seated dumbbell inner biceps curl',
    'spider curl',
    'standing biceps cable curl',
    'standing biceps stretch',
    'standing concentration curl',
    'standing dumbbell reverse curl',
    'standing inner-biceps curl',
    'standing one-arm cable curl',
    'standing one-arm dumbbell curl over incline bench',
    'two-arm dumbbell preacher curl',
    'wide-grip standing barbell curl',
    'zottman curl',
    'zottman preacher curl'
);

update exercises set muscle_group = 'shoulders'
where lower(name) in (
    'alternating cable shoulder press',
    'alternating deltoid raise',
    'alternating kettlebell press',
    'anti-gravity press',
    'arm circles',
    'arnold dumbbell press',
    'back flyes - with bands',
    'backward medicine ball throw',
    'band pull apart',
    'barbell incline shoulder raise',
    'barbell rear delt row',
    'barbell shoulder press',
    'barbell shrug',
    'barbell shrug behind the back',
    'battling ropes',
    'bent over dumbbell rear delt raise with head on bench',
    'bent over low-pulley side lateral',
    'bradford/rocky presses',
    'cable internal rotation',
    'cable rear delt fly',
    'cable rope rear-delt rows',
    'cable seated lateral raise',
    'cable shoulder press',
    'cable shrugs',
    'calf-machine shoulder shrug',
    'car drivers',
    'chair upper body stretch',
    'chin to chest stretch',
    'circus bell',
    'clean shrug',
    'clean and jerk',
    'clean and press',
    'crucifix',
    'cuban press',
    'double kettlebell jerk',
    'double kettlebell push press',
    'double kettlebell snatch',
    'dumbbell incline shoulder raise',
    'dumbbell lying one-arm rear lateral raise',
    'dumbbell lying rear lateral raise',
    'dumbbell one-arm shoulder press',
    'dumbbell one-arm upright row',
    'dumbbell raise',
    'dumbbell scaption',
    'dumbbell shoulder press',
    'dumbbell shrug',
    'elbow circles',
    'external rotation',
    'external rotation with band',
    'external rotation with cable',
    'face pull',
    'front cable raise',
    'front dumbbell raise',
    'front incline dumbbell raise',
    'front plate raise',
    'front two-dumbbell raise',
    'handstand push-ups',
    'internal rotation with band',
    'iron cross',
    'isometric neck exercise - front and back',
    'isometric neck exercise - sides',
    'jerk balance',
    'kettlebell arnold press',
    'kettlebell pirate ships',
    'kettlebell seated press',
    'kettlebell seesaw press',
    'kettlebell sumo high pull',
    'kettlebell thruster',
    'kettlebell turkish get-up (lunge style)',
    'kettlebell turkish get-up (squat style)',
    'kneeling arm drill',
    'landmine linear jammer',
    'lateral raise - with bands',
    'leverage shoulder press',
    'leverage shrug',
    'log lift',
    'low pulley row to neck',
    'lying face down plate neck resistance',
    'lying face up plate neck resistance',
    'lying one-arm lateral raise',
    'lying rear delt raise',
    'machine shoulder (military) press',
    'medicine ball scoop throw',
    'neck-smr',
    'one-arm incline lateral raise',
    'one-arm kettlebell clean and jerk',
    'one-arm kettlebell jerk',
    'one-arm kettlebell military press to the side',
    'one-arm kettlebell para press',
    'one-arm kettlebell push press',
    'one-arm kettlebell snatch',
    'one-arm kettlebell split jerk',
    'one-arm kettlebell split snatch',
    'one-arm side laterals',
    'power partials',
    'push press',
    'push press - behind the neck',
    'rack delivery',
    'return push from stance',
    'reverse flyes',
    'reverse flyes with external rotation',
    'reverse machine flyes',
    'round the world shoulder stretch',
    'scapular pull-up',
    'seated barbell military press',
    'seated bent-over rear delt raise',
    'seated cable shoulder press',
    'seated dumbbell press',
    'seated front deltoid',
    'seated head harness neck resistance',
    'seated side lateral raise',
    'see-saw press (alternating side press)',
    'shoulder circles',
    'shoulder press - with bands',
    'shoulder raise',
    'shoulder stretch',
    'side lateral raise',
    'side laterals to front raise',
    'side neck stretch',
    'side wrist pull',
    'single-arm linear jammer',
    'single dumbbell raise',
    'sled overhead backward walk',
    'sled reverse flye',
    'smith incline shoulder raise',
    'smith machine behind the back shrug',
    'smith machine one-arm upright row',
    'smith machine overhead shoulder press',
    'smith machine upright row',
    'snatch shrug',
    'standing alternating dumbbell press',
    'standing barbell press behind neck',
    'standing bradford press',
    'standing dumbbell press',
    'standing dumbbell straight-arm front delt raise above head',
    'standing dumbbell upright row',
    'standing front barbell raise over head',
    'standing low-pulley deltoid raise',
    'standing military press',
    'standing palm-in one-arm dumbbell press',
    'standing palms-in dumbbell press',
    'standing two-arm overhead throw',
    'straight raises on incline bench',
    'two-arm kettlebell clean',
    'two-arm kettlebell jerk',
    'two-arm kettlebell military press',
    'upright barbell row',
    'upright cable row',
    'upright row - with bands',
    'upward stretch'
);

update exercises set muscle_group = 'chest'
where lower(name) in (
    'alternating floor press',
    'around the worlds',
    'barbell bench press - medium grip',
    'barbell guillotine bench press',
    'barbell incline bench press - medium grip',
    'behind head chest stretch',
    'bench press - with bands',
    'bent-arm dumbbell pullover',
    'bodyweight flyes',
    'butterfly',
    'cable chest press',
    'cable crossover',
    'cable iron cross',
    'chain press',
    'chest and front of shoulder stretch',
    'chest push from 3 point stance',
    'chest push (multiple response)',
    'chest push (single response)',
    'chest push with run release',
    'chest stretch on stability ball',
    'clock push-up',
    'cross over - with bands',
    'decline barbell bench press',
    'decline dumbbell bench press',
    'decline dumbbell flyes',
    'decline push-up',
    'decline smith press',
    'dips - chest version',
    'drop push',
    'dumbbell bench press',
    'dumbbell bench press with neutral grip',
    'dumbbell flyes',
    'dynamic chest stretch',
    'elbows back',
    'extended range one-arm kettlebell floor press',
    'flat bench cable flyes',
    'forward drag with press',
    'front raise and pullover',
    'hammer grip incline db bench press',
    'heavy bag thrust',
    'incline cable chest press',
    'incline cable flye',
    'incline dumbbell bench with palms facing in',
    'incline dumbbell flyes',
    'incline dumbbell flyes - with a twist',
    'incline dumbbell press',
    'incline push-up',
    'incline push-up depth jump',
    'incline push-up medium',
    'incline push-up reverse grip',
    'incline push-up wide',
    'isometric chest squeezes',
    'isometric wipers',
    'leg-over floor press',
    'leverage chest press',
    'leverage decline chest press',
    'leverage incline chest press',
    'low cable crossover',
    'machine bench press',
    'medicine ball chest pass',
    'neck press',
    'one-arm flat bench dumbbell flye',
    'one-arm kettlebell floor press',
    'one arm dumbbell bench press',
    'plyo kettlebell pushups',
    'plyo push-up',
    'push-up wide',
    'push-ups with feet elevated',
    'push-ups with feet on an exercise ball',
    'push up to side plank',
    'pushups',
    'pushups (close and wide hand positions)',
    'single-arm cable crossover',
    'single-arm push-up',
    'smith machine bench press',
    'smith machine decline press',
    'smith machine incline bench press',
    'standing cable chest press',
    'straight-arm dumbbell pullover',
    'suspended push-up',
    'svend press',
    'wide-grip barbell bench press',
    'wide-grip decline barbell bench press',
    'wide-grip decline barbell pullover'
);

update exercises set muscle_group = 'back'
where lower(name) in (
    'alternating kettlebell row',
    'alternating renegade row',
    'atlas stone trainer',
    'atlas stones',
    'axle deadlift',
    'band assisted pull-up',
    'barbell deadlift',
    'bent-arm barbell pullover',
    'bent over barbell row',
    'bent over one-arm long bar row',
    'bent over two-arm long bar row',
    'bent over two-dumbbell row',
    'bent over two-dumbbell row with palms in',
    'bodyweight mid row',
    'cable incline pushdown',
    'cat stretch',
    'catch and overhead throw',
    'chair lower back stretch',
    'child''s pose',
    'chin-up',
    'close-grip front lat pulldown',
    'crossover reverse lunge',
    'dancer''s stretch',
    'deadlift with bands',
    'deadlift with chains',
    'deficit deadlift',
    'dumbbell incline row',
    'dynamic back stretch',
    'elevated cable rows',
    'full range-of-motion lat pulldown',
    'gironda sternum chins',
    'hug a ball',
    'hug knees to chest',
    'hyperextensions (back extensions)',
    'hyperextensions with no hyperextension bench',
    'incline bench pull',
    'inverted row',
    'inverted row with straps',
    'keg load',
    'kipping muscle up',
    'kneeling high pulley row',
    'kneeling single-arm high pulley row',
    'latissimus dorsi-smr',
    'leverage high row',
    'leverage iso row',
    'london bridges',
    'lower back-smr',
    'lying cambered barbell row',
    'lying t-bar row',
    'middle back shrug',
    'middle back stretch',
    'mixed grip chin',
    'muscle up',
    'one-arm dumbbell row',
    'one-arm kettlebell row',
    'one-arm long bar row',
    'one arm against wall',
    'one arm chin-up',
    'one arm lat pulldown',
    'one handed hang',
    'overhead lat',
    'overhead slam',
    'pelvic tilt into bridge',
    'pullups',
    'pyramid',
    'rack pull with bands',
    'rack pulls',
    'reverse band deadlift',
    'reverse grip bent-over rows',
    'rhomboids-smr',
    'rocky pull-ups/pulldowns',
    'rope climb',
    'rope straight-arm pulldown',
    'seated cable rows',
    'seated good mornings',
    'seated one-arm cable pulley rows',
    'shotgun row',
    'side-lying floor stretch',
    'side to side chins',
    'sled row',
    'smith machine bent over row',
    'spinal stretch',
    'standing pelvic tilt',
    'stiff leg barbell good morning',
    'straight-arm pulldown',
    'straight bar bench mid rows',
    'superman',
    'suspended row',
    't-bar row with handle',
    'two-arm kettlebell row',
    'underhand cable pulldowns',
    'upper back stretch',
    'v-bar pulldown',
    'v-bar pullup',
    'weighted ball hyperextension',
    'weighted pull ups',
    'wide-grip lat pulldown',
    'wide-grip pulldown behind the neck',
    'wide-grip rear pull-up'
);

update exercises set muscle_group = 'calves'
where lower(name) in (
    'ankle circles',
    'anterior tibialis-smr',
    'balance board',
    'barbell seated calf raise',
    'calf press',
    'calf press on the leg press machine',
    'calf raise on a dumbbell',
    'calf raises - with bands',
    'calf stretch elbows against wall',
    'calf stretch hands against wall',
    'calves-smr',
    'donkey calf raises',
    'dumbbell seated one-leg calf raise',
    'foot-smr',
    'knee circles',
    'peroneals-smr',
    'peroneals stretch',
    'posterior tibialis stretch',
    'rocking standing calf raise',
    'seated calf raise',
    'seated calf stretch',
    'smith machine calf raise',
    'smith machine reverse calf raises',
    'standing barbell calf raise',
    'standing calf raises',
    'standing dumbbell calf raise',
    'standing gastrocnemius calf stretch',
    'standing soleus and achilles stretch'
);

update exercises set muscle_group = 'glutes'
where lower(name) in (
    'ankle on the knee',
    'barbell glute bridge',
    'barbell hip thrust',
    'butt lift (bridge)',
    'downward facing balance',
    'flutter kicks',
    'glute kickback',
    'hip extension with bands',
    'hip lift with band',
    'knee across the body',
    'kneeling jump squat',
    'kneeling squat',
    'leg lift',
    'lying glute',
    'one-legged cable kickback',
    'one knee to chest',
    'physioball hip bridge',
    'piriformis-smr',
    'pull through',
    'seated glute',
    'single leg glute bridge',
    'step-up with knee raise'
);

update exercises set muscle_group = 'triceps'
where lower(name) in (
    'band skull crusher',
    'bench dips',
    'bench press - powerlifting',
    'bench press with chains',
    'board press',
    'body-up',
    'body tricep press',
    'cable incline triceps extension',
    'cable lying triceps extension',
    'cable one arm tricep extension',
    'cable rope overhead triceps extension',
    'chain handle extension',
    'close-grip barbell bench press',
    'close-grip dumbbell press',
    'close-grip ez-bar press',
    'close-grip push-up off of a dumbbell',
    'decline close-grip bench to skull crusher',
    'decline dumbbell triceps extension',
    'decline ez bar triceps extension',
    'dip machine',
    'dips - triceps version',
    'dumbbell floor press',
    'dumbbell one-arm triceps extension',
    'dumbbell tricep extension -pronated grip',
    'ez-bar skullcrusher',
    'floor press',
    'floor press with chains',
    'incline barbell triceps extension',
    'incline push-up close-grip',
    'jm press',
    'kneeling cable triceps extension',
    'low cable triceps extension',
    'lying close-grip barbell triceps extension behind the head',
    'lying close-grip barbell triceps press to chin',
    'lying dumbbell tricep extension',
    'lying triceps press',
    'machine triceps extension',
    'one arm floor press',
    'one arm pronated dumbbell triceps extension',
    'one arm supinated dumbbell triceps extension',
    'overhead triceps',
    'parallel bar dip',
    'pin presses',
    'push-ups - close triceps position',
    'reverse band bench press',
    'reverse grip triceps pushdown',
    'reverse triceps bench press',
    'ring dips',
    'seated bent-over one-arm dumbbell triceps extension',
    'seated bent-over two-arm dumbbell triceps extension',
    'seated triceps press',
    'sled overhead triceps extension',
    'smith machine close-grip bench press',
    'speed band overhead triceps',
    'standing bent-over one-arm dumbbell triceps extension',
    'standing bent-over two-arm dumbbell triceps extension',
    'standing dumbbell triceps extension',
    'standing low-pulley one-arm triceps extension',
    'standing one-arm dumbbell triceps extension',
    'standing overhead barbell triceps extension',
    'standing towel triceps extension',
    'supine chest throw',
    'tate press',
    'tricep dumbbell kickback',
    'tricep side stretch',
    'triceps overhead extension with rope',
    'triceps pushdown',
    'triceps pushdown - rope attachment',
    'triceps pushdown - v-bar attachment',
    'triceps stretch',
    'weighted bench dip'
);

update exercises set muscle_group = 'forearms'
where lower(name) in (
    'bottoms-up clean from the hang position',
    'cable wrist curl',
    'dumbbell lying pronation',
    'dumbbell lying supination',
    'farmer''s walk',
    'finger curls',
    'kneeling forearm stretch',
    'palms-down dumbbell wrist curl over a bench',
    'palms-down wrist curl over a bench',
    'palms-up barbell wrist curl over a bench',
    'palms-up dumbbell wrist curl over a bench',
    'plate pinch',
    'rickshaw carry',
    'seated dumbbell palms-down wrist curl',
    'seated dumbbell palms-up wrist curl',
    'seated one-arm dumbbell palms-down wrist curl',
    'seated one-arm dumbbell palms-up wrist curl',
    'seated palm-up barbell wrist curl',
    'seated palms-down barbell wrist curl',
    'seated two-arm palms-up low-pulley wrist curl',
    'standing olympic plate hand squeeze',
    'standing palms-up barbell behind the back wrist curl',
    'wrist circles',
    'wrist roller',
    'wrist rotations with straight bar'
);

-- Step 3: Fix any remaining old broad values not caught by name matching
update exercises set muscle_group = 'biceps'   where muscle_group = 'arms';
update exercises set muscle_group = 'chest'    where muscle_group = 'cardio';
update exercises set muscle_group = 'glutes'   where muscle_group = 'butt';

-- Step 4: Safety net — catch anything still not in the new allowed list
update exercises set muscle_group = 'abs'
where muscle_group not in ('chest','back','legs','shoulders','biceps','triceps','forearms','abs','glutes','calves');

-- Step 5: Add new constraint
alter table exercises
  add constraint exercises_muscle_group_check
  check (muscle_group in ('chest','back','legs','shoulders','biceps','triceps','forearms','abs','glutes','calves'));
