-- Auto-generated exercise seed (free-exercise-db)
-- Generated: 2026-05-14T23:59:41.951Z
-- Total: 98 exercises

-- Clear dependent data before deleting exercises
delete from set_completions
where workout_exercise_id in (
  select we.id from workout_exercises we
  join exercises e on e.id = we.exercise_id
  where e.created_by is null
);
delete from workout_exercises
where exercise_id in (select id from exercises where created_by is null);
delete from exercises where created_by is null;

insert into exercises (name, muscle_group, image_url) values
  ('Barbell Bench Press - Medium Grip', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg'),
  ('Decline Barbell Bench Press', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg'),
  ('Wide-Grip Barbell Bench Press', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Barbell_Bench_Press/0.jpg'),
  ('Wide-Grip Decline Barbell Bench Press', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Decline_Barbell_Bench_Press/0.jpg'),
  ('Incline Dumbbell Bench With Palms Facing In', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Bench_With_Palms_Facing_In/0.jpg'),
  ('Incline Dumbbell Flyes', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes/0.jpg'),
  ('Incline Dumbbell Flyes - With A Twist', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Flyes_-_With_A_Twist/0.jpg'),
  ('Incline Dumbbell Press', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg'),
  ('Wide-Grip Decline Barbell Pullover', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Decline_Barbell_Pullover/0.jpg'),
  ('Clock Push-Up', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clock_Push-Up/0.jpg'),
  ('Decline Push-Up', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg'),
  ('Incline Push-Up', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up/0.jpg'),
  ('Incline Push-Up Medium', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up_Medium/0.jpg'),
  ('Incline Push-Up Reverse Grip', 'chest', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up_Reverse_Grip/0.jpg'),
  ('Band Assisted Pull-Up', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Band_Assisted_Pull-Up/0.jpg'),
  ('Rocky Pull-Ups/Pulldowns', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocky_Pull-Ups_Pulldowns/0.jpg'),
  ('Wide-Grip Rear Pull-Up', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Rear_Pull-Up/0.jpg'),
  ('Pullups', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg'),
  ('V-Bar Pullup', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pullup/0.jpg'),
  ('Barbell Deadlift', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg'),
  ('Chin-Up', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg'),
  ('One Arm Chin-Up', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Arm_Chin-Up/0.jpg'),
  ('Scapular Pull-Up', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Scapular_Pull-Up/0.jpg'),
  ('Bent Over Barbell Row', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg'),
  ('Close-Grip Front Lat Pulldown', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg'),
  ('Full Range-Of-Motion Lat Pulldown', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Full_Range-Of-Motion_Lat_Pulldown/0.jpg'),
  ('One Arm Lat Pulldown', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One_Arm_Lat_Pulldown/0.jpg'),
  ('Wide-Grip Lat Pulldown', 'back', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg'),
  ('One-Arm Side Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Side_Deadlift/0.jpg'),
  ('Romanian Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg'),
  ('Stiff-Legged Barbell Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Barbell_Deadlift/0.jpg'),
  ('Stiff-Legged Dumbbell Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg'),
  ('Cable Deadlifts', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Deadlifts/0.jpg'),
  ('Kettlebell One-Legged Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_One-Legged_Deadlift/0.jpg'),
  ('Leverage Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Deadlift/0.jpg'),
  ('Smith Machine Stiff-Legged Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Smith_Machine_Stiff-Legged_Deadlift/0.jpg'),
  ('Trap Bar Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Trap_Bar_Deadlift/0.jpg'),
  ('Clean Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Clean_Deadlift/0.jpg'),
  ('Reverse Band Sumo Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Band_Sumo_Deadlift/0.jpg'),
  ('Romanian Deadlift from Deficit', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift_from_Deficit/0.jpg'),
  ('Snatch Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Snatch_Deadlift/0.jpg'),
  ('Sumo Deadlift', 'legs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg'),
  ('Front Incline Dumbbell Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Incline_Dumbbell_Raise/0.jpg'),
  ('Handstand Push-Ups', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Handstand_Push-Ups/0.jpg'),
  ('Upright Barbell Row', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg'),
  ('Face Pull', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg'),
  ('Kettlebell Turkish Get-Up (Squat style)', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Squat_style/0.jpg'),
  ('Kettlebell Turkish Get-Up (Lunge style)', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Turkish_Get-Up_Lunge_style/0.jpg'),
  ('Dumbbell Lying One-Arm Rear Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_One-Arm_Rear_Lateral_Raise/0.jpg'),
  ('Dumbbell Lying Rear Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lying_Rear_Lateral_Raise/0.jpg'),
  ('Lying One-Arm Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_One-Arm_Lateral_Raise/0.jpg'),
  ('One-Arm Incline Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Incline_Lateral_Raise/0.jpg'),
  ('Seated Side Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Side_Lateral_Raise/0.jpg'),
  ('Side Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg'),
  ('Kettlebell Arnold Press', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kettlebell_Arnold_Press/0.jpg'),
  ('Cable Seated Lateral Raise', 'shoulders', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Lateral_Raise/0.jpg'),
  ('Close-Grip Barbell Bench Press', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg'),
  ('Alternate Incline Dumbbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Incline_Dumbbell_Curl/0.jpg'),
  ('Flexor Incline Dumbbell Curls', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flexor_Incline_Dumbbell_Curls/0.jpg'),
  ('Incline Dumbbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg'),
  ('Close-Grip Push-Up off of a Dumbbell', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Push-Up_off_of_a_Dumbbell/0.jpg'),
  ('Incline Push-Up Close-Grip', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Push-Up_Close-Grip/0.jpg'),
  ('Push-Ups - Close Triceps Position', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_-_Close_Triceps_Position/0.jpg'),
  ('Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg'),
  ('Barbell Curls Lying Against An Incline', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curls_Lying_Against_An_Incline/0.jpg'),
  ('Close-Grip Standing Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Standing_Barbell_Curl/0.jpg'),
  ('Lying High Bench Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_High_Bench_Barbell_Curl/0.jpg'),
  ('Reverse Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Barbell_Curl/0.jpg'),
  ('Seated Close-Grip Concentration Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Close-Grip_Concentration_Barbell_Curl/0.jpg'),
  ('Wide-Grip Standing Barbell Curl', 'arms', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Standing_Barbell_Curl/0.jpg'),
  ('Cross-Body Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cross-Body_Crunch/0.jpg'),
  ('Decline Oblique Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Oblique_Crunch/0.jpg'),
  ('Decline Reverse Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Reverse_Crunch/0.jpg'),
  ('Gorilla Chin/Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Gorilla_Chin_Crunch/0.jpg'),
  ('Bosu Ball Cable Crunch With Side Bends', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bosu_Ball_Cable_Crunch_With_Side_Bends/0.jpg'),
  ('Cable Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg'),
  ('Cable Reverse Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Reverse_Crunch/0.jpg'),
  ('Cable Seated Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Crunch/0.jpg'),
  ('Kneeling Cable Crunch With Alternating Oblique Twists', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists/0.jpg'),
  ('Rope Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Crunch/0.jpg'),
  ('Standing Rope Crunch', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Rope_Crunch/0.jpg'),
  ('Ab Crunch Machine', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg'),
  ('Crunch - Hands Overhead', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch_-_Hands_Overhead/0.jpg'),
  ('Crunch - Legs On Exercise Ball', 'abs', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch_-_Legs_On_Exercise_Ball/0.jpg'),
  ('Kneeling Jump Squat', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kneeling_Jump_Squat/0.jpg'),
  ('Kneeling Squat', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Kneeling_Squat/0.jpg'),
  ('Pull Through', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pull_Through/0.jpg'),
  ('Flutter Kicks', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flutter_Kicks/0.jpg'),
  ('Glute Kickback', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/0.jpg'),
  ('Hip Extension with Bands', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hip_Extension_with_Bands/0.jpg'),
  ('Physioball Hip Bridge', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Physioball_Hip_Bridge/0.jpg'),
  ('Step-up with Knee Raise', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step-up_with_Knee_Raise/0.jpg'),
  ('One-Legged Cable Kickback', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Legged_Cable_Kickback/0.jpg'),
  ('Barbell Glute Bridge', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg'),
  ('Barbell Hip Thrust', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg'),
  ('Butt Lift (Bridge)', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butt_Lift_Bridge/0.jpg'),
  ('Downward Facing Balance', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Downward_Facing_Balance/0.jpg'),
  ('Leg Lift', 'butt', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Lift/0.jpg');
